import Head from 'next/head'


import About from './about'
import Dsce from './dsce'

import Hero from './hero'
import Page from './page'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        
         <About />
         <Page />
         <Dsce />
       
       
    </div>
  )
}
