import Head from 'next/head'


import About from './about'
import Dsce from './dsce'

import Hero from './hero'
import Page from './page'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>ICAETIS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://imgs.search.brave.com/GKXrhovF8kXhQmV22IOr5EchlZxdaY9u_M6ND2JilcM/rs:fit:200:200:1/g:ce/aHR0cHM6Ly9pbWcu/Y29sbGVnZXByYXZl/c2guY29tLzIwMTgv/MTAvRFNJLUJhbmdh/bG9yZS1Mb2dvLnBu/Zw" />
      </Head>

        
         <About />
         <Page />
         <Dsce />
       
       
    </div>
  )
}
